# @package _global_
defaults:
  - base
  - _self_

expname: BONES-SEED-FUTURE-64-ROT-MAT-VAE
task: train-mvae

data:
  datadir: ./dataset/BONES-SEED-29dof-FULL-50fps
  dof_dim: 29
  load_goal_stats: false
  preload_ram: true
  load_scene: false
  num_primitive: 3
  batch_size: 256
  weighted_sample: true

train:
  manager:
    use_rollout: true

skeleton:
  asset:
    assetRoot: ./description/robots/g1/
