_target_: robotmdar.model.mld_denoiser.DenoiserTransformer
h_dim: 512
ff_size: 1024
num_layers: 8
num_heads: 4
dropout: 0.1
activation: gelu
history_shape:
  - 2
  - ${...nfeats}
noise_shape: [1, 128]
goal_dim: 5
grid_size: 25
cond_goal_mask_prob: 0.1
cond_scene_mask_prob: 0.8
