_target_: robotmdar.model.mld_denoiser.DenoiserTransformer
h_dim: 512
ff_size: 1024
num_layers: 8
num_heads: 4
dropout: 0.1
activation: gelu
history_shape:
  - ${...data.history_len}
  - ${...nfeats}
noise_shape: [1, 128]
clip_dim: 512
goal_encoding: split
goal_dim: 5
grid_size: 25
cond_mask_prob:
  text: 0.1
  goal:
    position: 0.1
    yaw: 0.0
    time: 0.0
    body: 0.0
    orientation: 0.0
    joint: 0.0
    velocity: 0.0
  scene: 1.0
